// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNZJpF2Phi0iUFdtw4Rd3SI0iHynGloUU',
    appId: '1:691253213364:web:b59546d0b34c3c846cffe1',
    messagingSenderId: '691253213364',
    projectId: 'crud-248e8',
    authDomain: 'crud-248e8.firebaseapp.com',
    storageBucket: 'crud-248e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4eUfFuGsOe1HrnnEmBROfZHvfcyL6j8o',
    appId: '1:691253213364:android:4c1b4fd41d0a6da16cffe1',
    messagingSenderId: '691253213364',
    projectId: 'crud-248e8',
    storageBucket: 'crud-248e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeL0rfaaoCBm9KwKGhoVhv8PMnZeWsPRQ',
    appId: '1:691253213364:ios:f4e25b94916d5a296cffe1',
    messagingSenderId: '691253213364',
    projectId: 'crud-248e8',
    storageBucket: 'crud-248e8.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeL0rfaaoCBm9KwKGhoVhv8PMnZeWsPRQ',
    appId: '1:691253213364:ios:9501503846ab5c946cffe1',
    messagingSenderId: '691253213364',
    projectId: 'crud-248e8',
    storageBucket: 'crud-248e8.appspot.com',
    iosBundleId: 'com.example.first.RunnerTests',
  );
}
